owner: waisimon # GitHub username
repo: uptime # GitHub repository name
sites: # List of endpoints to track
  - name: Google
    url: https://www.google.com
  - name: Bet2Me
    url: $WH_BET2ME
assignees: # Users to assign downtime issues (optional)
  - waisimon
status-website:
  baseUrl: /uptime # where "repo" is your repository name
  name: Up or Down
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
