owner: waisimon # GitHub username
repo: uptime # GitHub repository name
sites: # List of endpoints to track
  - name: Google
    url: https://www.google.com
assignees: # Users to assign downtime issues (optional)
  - waisimon
status-website:
  baseUrl: /uptime # where "repo" is your repository name
  name: Your Status Website
